import os, time
for i in range(100):
    os.system('cls')
    print("Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ Loading    \ ")
    time.sleep(0.15)
    os.system('cls')
    print("Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | Loading.   | ")
    time.sleep(0.15)
    os.system('cls')
    print("Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / Loading..  / ")
    time.sleep(0.15)
    os.system('cls')
    print("Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - Loading... - ")
    time.sleep(0.15)

